### ISSUE TITLE
[Bug] Segfault on test/method/too_many_parameters.morpho

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho#107]
**Describe the bug**
[This](https://github.com/Morpho-lang/morpho/blob/main/test/method/too_many_parameters.morpho) test segfaults.

**Comment by softmattertheory** [comment]
This bug is very pernicious! L2326-7 in compiler_function in compile.c place a static string "self" to refer to r0 in a method declaration. Being a static string, this lives on the C stack. However, under some circumstances, this can end up being read after compiler_function has returned, triggering an abort. I will fix.
