### ISSUE TITLE
Bug when putting in an empty index

### ISSUE THREAD

**Issue by Craftyleosteel** [Morpho-lang/morpho#237]
Morpho reports a development error when you don't index by anything. We should probably have an error for this something like:

Err: Empty Index

**Comment by softmattertheory** [comment]
Thanks so much for reporting this @Craftyleosteel, and apologies for the delay! I note that this is quite serious since it generates the error "Internal consistency error: Please contact developer. [Explanation: compiling an unexpectedly blank node [run with debugger]]." We should replace this with a user-friendly message.

**Comment by softmattertheory** [comment]
We're happy to note this has been fixed in the imminent v0.6.0 release, thanks for raising this issue @Craftyleosteel!
