### ISSUE TITLE
[Bug] `if (isinf(1)) print "Welp!"` outputs "Welp!"

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho#46]
**Describe the bug**
There are two things going on here:
1. The documentation says the `isinf` function returns `true` if a value is infinite or `false` otherwise, but in reality, it returns `1` if it's `+inf`, `0` if it's finite and `-1` if it's `-inf`. and
2. `if` doesn't treat `0` as `false` and anything non-zero as `true`. 

So something like
`if (isinf(1)) print "Welp!"`
outputs "Welp!"

**Comment by softmattertheory** [comment]
For 2) In Morpho the only things that are false are 'nil' and 'false' — everything else is true. This greatly helps simplify things and should be easier to remember. I don't want to change this. 

To resolve this however, we could:—

A) make isinf return false for not infinite and +1/-1 otherwise (both of which would evaluate to true) 

B) make isinf simply return true or false and check that sign() [Issue #44 ] returns +1/-1 for +inf/-inf... 

What do you think @joshichaitanya3  and @ConduitDan ? I have a mild preference for B...

**Comment by joshichaitanya3** [comment]
That makes sense. I also have a preference for B.

**Comment by ConduitDan** [comment]
I too have a preference for B
